# Generated by Django 5.0.4 on 2024-04-13 10:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MainApp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='sitesetting',
            name='aboutImage',
            field=models.ImageField(blank=True, null=True, upload_to='uploads/'),
        ),
    ]
