# Generated by Django 5.0.4 on 2024-04-13 10:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('MainApp', '0002_sitesetting_aboutimage'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Sermom',
            new_name='Sermon',
        ),
    ]
