# Generated by Django 5.0.4 on 2024-04-15 17:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MainApp', '0004_livevideo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='livevideo',
            name='url',
            field=models.TextField(),
        ),
    ]
