# Generated by Django 5.0.4 on 2024-04-15 17:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MainApp', '0005_alter_livevideo_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='livevideo',
            name='pastorMessage',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='livevideo',
            name='url',
            field=models.TextField(blank=True, null=True),
        ),
    ]
